### ISSUE TITLE
Bug with Fill extension method

### ISSUE THREAD

**Issue by stazz** [mykohsu/Extensions#1]
There is a bug in the array filling extension method.
For example, this test case will reproduce the error:

``` cs
         var array = new Int32[3];
         array.Fill( 6 );
         Assert.IsTrue( array.All( i => i == 6 ) );
```

This is due to the fact that when control flow arrives to the final Array.Copy after a for loop, less that half of an array is filled.

**Comment by stazz** [comment]
I was able to fix it (test case ran through arrays of size from 1 to UInt16.MaxValue and succeeded for all of them) by changing the loop part into this:

``` cs
         int destinationLen = destinationArray.Length;
         int copyLength;

         for ( copyLength = value.Length; copyLength + copyLength < destinationLen; copyLength <<= 1 )
         {
            Array.Copy( destinationArray, 0, destinationArray, copyLength, copyLength );
         }
```

**Comment by mykohsu** [comment]
Good catch. The issue is for a specific case where the array is of odd length and the fill pattern is exactly (length - 1) / 2.

There are a couple of ways to fix this, one of which you proposed. Another is to increment arrayToFillHalfLength by 1 when the pattern has an odd length.
